name: integracion continua node.js

on: 
  pull_request:
    branches: [merge/main1]
  
jobs: 
  ci_to_main:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: yarn install
      - run: yarn test
      